jobs:
  workflow:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Install Libraries
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./verify/build

name: Action

on:
  schedule:
    - cron: "20 0/3 * * *"
